### ISSUE TITLE
Clock level does nothing on linux

### ISSUE THREAD

**Issue by adrianheine** [jthwho/SickBeatBetty#2]
Compiling on linux was straightforward. However, the clock levels are not taken into account for beat level, as you can see on the color in the beat grid:
![image](https://user-images.githubusercontent.com/139208/209574487-7c372429-2363-4179-8f47-61fea87cc5c2.png)

(this is a reproduction of one gen of the toms break in https://www.youtube.com/watch?v=SQi-Ny8AE8I)

**Comment by jthwho** [comment]
Odd, not sure why Linux would be different but I'll see if I can reproduce it.  In the meantime, try changing the level of clock 3 and see if that effects things (with Euclid disabled and the rate set to a large / indivisible value).  Thanks for the feedback, hope you're otherwise finding it useful.

**Comment by adrianheine** [comment]
That didn't change anything, unfortunately. I don't understand why it would not work, but I can try to debug if you give me some pointers.

**Comment by jthwho** [comment]
Hmm.  The actual beat generation happens in BeatGen::updateBeats().  In particular the line `beat.velocity = beatClock[i] ? levelAtPhase(beat.start) : 0.0;` is responsible for assigning the velocity to the beat, so that's a good place to start.  Probably taking a look at the levelAtPhase() function next would be the next step.  I've also got a commented out printf() in the generate() function that'll dump all the beats and their respective timing and velocity.. probably doing something like that at different points will get you to an answer.

Running it standalone in a debugger would also be an option as debugging in the DAW can be a PITA.
